### ISSUE TITLE
Svelte 5

### ISSUE THREAD

**Issue by cloudlena** [K-Sato1995/svelte-vertical-timeline#28]
It would be amazing if this project supported Svelte 5. Currently, it's the only thing holding my website back from upgrading to Svelte 5 😊.

**Comment by K-Sato1995** [comment]
@cloudlena 
Thank you for commenting! I'll work on that as soon as i get some free time!

**Comment by evdama** [comment]
Really nice package... I'd also like to use it in some Svelte 5 apps once it's ready 👍

**Comment by K-Sato1995** [comment]
@cloudlena @evdama 

It should work with Sveltev5 if u upgrade this package to the latest version (v2.0.0)
Thanks for creating the issue🙏!

https://github.com/K-Sato1995/svelte-vertical-timeline/releases/tag/v2.0.0
