### ISSUE TITLE
Warning with SvelteKit

### ISSUE THREAD

**Issue by cloudlena** [K-Sato1995/svelte-vertical-timeline#6]
When running `npm run build` in a SvelteKit application, I get the following warning:

```txt
3:10:59 PM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-vertical-timeline@1.0.0

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

**Comment by K-Sato1995** [comment]
@cloudlena 

Thanks!!
The PR below should address this issue but haven't had time to work on it.

- https://github.com/K-Sato1995/svelte-vertical-timeline/pull/5

**Comment by K-Sato1995** [comment]
fixed with https://github.com/K-Sato1995/svelte-vertical-timeline/pull/5

**Comment by cloudlena** [comment]
Awesome! Thank you, @K-Sato1995.

**Comment by cloudlena** [comment]
@K-Sato1995, with the new version, the above warning seems to be fixed. However, now I get another error when running `npm run check` in a SvelteKit project:

```txt
Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
/home/lena/Projects/bespinian/bespinian.io/src/routes/Services.svelte:20:9
Error: Cannot find module 'svelte-vertical-timeline' or its corresponding type declarations. (ts)
                TimelineContent
        } from 'svelte-vertical-timeline';
```

**Comment by K-Sato1995** [comment]
@cloudlena 

hey yeah my bad!
I'll upgrade the deps and fix the export stuff with this pr https://github.com/K-Sato1995/svelte-vertical-timeline/pull/7

**Comment by K-Sato1995** [comment]
@cloudlena 

The pkg should export types properly now🙏
Thanks for creating an issue🙏

https://github.com/K-Sato1995/svelte-vertical-timeline/pull/7

**Comment by cloudlena** [comment]
Works like a charm. Thanks, @K-Sato1995!
